### PR TITLE
Tweak visual weights

### PR DESCRIPTION
**Pull request by psql**

### CODE REVIEW

**Comment by psql** [comment]
@dubstrike Do you have a SCSS compiler you like to use?

**Comment by pugson** [comment]
@pasql I'll compile this manually with CodeKit this time and set up gulp for the task. Thanks for the changes!

**Comment by Pasql** [comment]
@psql ;)

**Comment by pugson** [comment]
Hah, sorry @pasql

**Comment by pugson** [comment]
@psql I just added `gulp` to the project, so it's easy to contribute to. Check out the [updated readme](https://github.com/dubstrike/twitter-dark-mode/blob/master/README.md#contributing)

**Pull request merged**
